table dim_market
	lineageTag: a8bac2bc-e61a-4f62-a90e-8da5afbcc998

	column market
		dataType: string
		lineageTag: 6db90f36-2d7d-4653-85f9-481621c39faa
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column sub_zone
		dataType: string
		lineageTag: 826878f4-8350-4182-87e5-e8e83e20d56a
		summarizeBy: none
		sourceColumn: sub_zone

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 7f1c4f55-41ac-4371-97f1-4baa4d52fb5c
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_market = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = MySQL.Database("localhost", "gdb041", [ReturnSingleDatabase=true]),
				    gdb041_dim_market = Source{[Schema="gdb041",Item="dim_market"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(gdb041_dim_market,"nan","NA",Replacer.ReplaceText,{"sub_zone"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","nan","NA",Replacer.ReplaceText,{"region"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

