table fact_forecast_monthly
	lineageTag: 480ffa8c-ff4f-414b-8b65-1c112872c335

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 64e28878-d296-452c-a816-88ae0c0a59a2
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column product_code
		dataType: string
		lineageTag: 00baf86d-415e-4d3d-ab3c-1d51ba28a8ff
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column customer_code
		dataType: string
		lineageTag: d03d55f7-2139-4048-af4a-bb2f831c4788
		summarizeBy: none
		sourceColumn: customer_code

		annotation SummarizationSetBy = Automatic

	column forecast_quantity
		dataType: int64
		formatString: 0
		lineageTag: 1f3fb655-5a25-4185-ab33-afe62d37add3
		summarizeBy: sum
		sourceColumn: forecast_quantity

		annotation SummarizationSetBy = Automatic

	partition fact_forecast_monthly = m
		mode: import
		queryGroup: facts_group
		source =
				let
				    Source = MySQL.Database("localhost", "gdb041", [ReturnSingleDatabase=true]),
				    gdb041_fact_forecast_monthly = Source{[Schema="gdb041",Item="fact_forecast_monthly"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(gdb041_fact_forecast_monthly,{"date", "product_code", "customer_code", "forecast_quantity"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

